# .github/dependabot.yml
# Dependabot configuration for automated dependency updates

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for package.json and lock files in the root directory
    directory: "/"
    # Check for updates weekly on Mondays
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/New_York"
    # Limit the number of open pull requests for version updates
    open-pull-requests-limit: 10
    # Group minor and patch updates together to reduce PR noise
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Add descriptive commit messages
    commit-message:
      prefix: "deps"
      include: "scope"
