# GCP Cloud Build configuration for automated dependency management
# Replaces GitHub Dependabot with GCP-native solution
steps:
  # Step 1: Install dependencies and tools
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install', '--production=false']
    
  # Step 2: Check for outdated packages and security vulnerabilities
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "${_SECURITY_ONLY}" = "true" ]; then
          echo "ðŸ”’ Security-focused scan: Checking for vulnerabilities only..."
          npm audit --json > /workspace/audit.json || true
          echo "{}" > /workspace/outdated.json
        else
          echo "ðŸ” Full dependency scan: Checking for outdated dependencies and vulnerabilities..."
          npm outdated --json > /workspace/outdated.json || true
          npm audit --json > /workspace/audit.json || true
        fi
        
  # Step 3: Run dependency analysis script
  - name: 'node:18'
    entrypoint: 'node'
    args: ['/workspace/scripts/dependency-analyzer.js']
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'REPO_OWNER=${_REPO_OWNER}'
      - 'REPO_NAME=${_REPO_NAME}'
      - 'GITHUB_TOKEN=${_GITHUB_TOKEN}'
    secretEnv: ['GITHUB_TOKEN']
    
  # Step 4: Security vulnerability scan
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "ðŸ”’ Running security scan..."
        gcloud components install local-extract --quiet
        gcloud beta container images scan /workspace --format=json > /workspace/security-scan.json || true
        
  # Step 5: Create GitHub pull requests for critical updates
  - name: 'node:18'
    entrypoint: 'node'
    args: ['/workspace/scripts/github-pr-creator.js']
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'REPO_OWNER=${_REPO_OWNER}'
      - 'REPO_NAME=${_REPO_NAME}'
    secretEnv: ['GITHUB_TOKEN']

# Available secrets from Secret Manager
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/github-token/versions/latest
      env: 'GITHUB_TOKEN'

# Substitutions for flexibility
substitutions:
  _REPO_OWNER: 'jimmy058910'
  _REPO_NAME: 'realm-rivalry'
  _BRANCH_NAME: 'gcp-dependency-updates'
  _SECURITY_ONLY: 'false'

# Options
options:
  machineType: 'E2_MEDIUM'
  logging: CLOUD_LOGGING_ONLY

# Timeout
timeout: '1200s'