import express from 'express';
import { simulateEnhancedMatch } from '../services/matchSimulation';
import { Player } from '../../generated/prisma';

const router = express.Router();

// Demo endpoint using the real match simulation system
router.post('/match-simulation', async (req, res) => {
  try {
    // Create realistic demo players with proper Realm Rivalry attributes
    const homeTeamPlayers: Player[] = [
      {
        id: 1,
        firstName: 'Alex',
        lastName: 'Thunder',
        race: 'HUMAN',
        role: 'PASSER',
        speed: 28,
        power: 26,
        throwing: 32,
        catching: 24,
        kicking: 20,
        staminaAttribute: 30,
        leadership: 29,
        agility: 25,
        potentialRating: 3.5,
        age: 24,
        teamId: 101,
        createdAt: new Date(),
        updatedAt: new Date(),
        dailyStaminaLevel: 100,
        injuryStatus: 'HEALTHY',
        injuryRecoveryPointsNeeded: 0,
        injuryRecoveryPointsCurrent: 0,
        dailyItemsUsed: [],
        careerInjuries: 0,
        gamesPlayedLastSeason: 12,
        seasonMinutesLeague: 840,
        seasonMinutesTotal: 840,
        isOnMarket: false,
        isRetired: false,
        camaraderieScore: 75,
      },
      {
        id: 2,
        firstName: 'Mike',
        lastName: 'Blitz',
        race: 'SYLVAN',
        role: 'RUNNER',
        speed: 35,
        power: 23,
        throwing: 18,
        catching: 28,
        kicking: 15,
        staminaAttribute: 28,
        leadership: 22,
        agility: 36,
        potentialRating: 4.0,
        age: 22,
        teamId: 101,
        createdAt: new Date(),
        updatedAt: new Date(),
        dailyStaminaLevel: 100,
        injuryStatus: 'HEALTHY',
        injuryRecoveryPointsNeeded: 0,
        injuryRecoveryPointsCurrent: 0,
        dailyItemsUsed: [],
        careerInjuries: 0,
        gamesPlayedLastSeason: 12,
        seasonMinutesLeague: 840,
        seasonMinutesTotal: 840,
        isOnMarket: false,
        isRetired: false,
        camaraderieScore: 75,
        dailyItemsUsed: 0,
        careerInjuries: 0,
        gamesPlayedLastSeason: 0,
        seasonMinutesLeague: 0,
        seasonMinutesTournament: 0,
        seasonMinutesExhibition: 0,
      },
      {
        id: 3,
        firstName: 'Sarah',
        lastName: 'Strike',
        race: 'GRYLL',
        role: 'BLOCKER',
        speed: 22,
        power: 38,
        throwing: 16,
        catching: 25,
        kicking: 18,
        staminaAttribute: 35,
        leadership: 28,
        agility: 24,
        potentialRating: 3.2,
        age: 26,
        teamId: 101,
        createdAt: new Date(),
        updatedAt: new Date(),
        dailyStaminaLevel: 100,
        injuryStatus: 'HEALTHY',
        injuryRecoveryPointsNeeded: 0,
        injuryRecoveryPointsCurrent: 0,
        dailyItemsUsed: [],
        careerInjuries: 0,
        gamesPlayedLastSeason: 12,
        seasonMinutesLeague: 840,
        seasonMinutesTotal: 840,
        isOnMarket: false,
        isRetired: false,
        camaraderieScore: 75,
        dailyItemsUsed: 0,
        careerInjuries: 0,
        gamesPlayedLastSeason: 0,
        seasonMinutesLeague: 0,
        seasonMinutesTournament: 0,
        seasonMinutesExhibition: 0,
      }
    ];

    const awayTeamPlayers: Player[] = [
      {
        id: 4,
        firstName: 'Jake',
        lastName: 'Storm',
        race: 'LUMINA',
        role: 'PASSER',
        speed: 26,
        power: 24,
        throwing: 34,
        catching: 22,
        kicking: 25,
        staminaAttribute: 27,
        leadership: 32,
        agility: 23,
        potentialRating: 4.2,
        age: 25,
        teamId: 102,
        createdAt: new Date(),
        updatedAt: new Date(),
        dailyStaminaLevel: 100,
        injuryStatus: 'HEALTHY',
        injuryRecoveryPointsNeeded: 0,
        injuryRecoveryPointsCurrent: 0,
        dailyItemsUsed: [],
        careerInjuries: 0,
        gamesPlayedLastSeason: 12,
        seasonMinutesLeague: 840,
        seasonMinutesTotal: 840,
        isOnMarket: false,
        isRetired: false,
        camaraderieScore: 75,
        dailyItemsUsed: 0,
        careerInjuries: 0,
        gamesPlayedLastSeason: 0,
        seasonMinutesLeague: 0,
        seasonMinutesTournament: 0,
        seasonMinutesExhibition: 0,
      },
      {
        id: 5,
        firstName: 'Lisa',
        lastName: 'Bolt',
        race: 'UMBRA',
        role: 'RUNNER',
        speed: 31,
        power: 25,
        throwing: 19,
        catching: 30,
        kicking: 16,
        staminaAttribute: 26,
        leadership: 20,
        agility: 33,
        potentialRating: 3.8,
        age: 23,
        teamId: 102,
        createdAt: new Date(),
        updatedAt: new Date(),
        dailyStaminaLevel: 100,
        injuryStatus: 'HEALTHY',
        injuryRecoveryPointsNeeded: 0,
        injuryRecoveryPointsCurrent: 0,
        dailyItemsUsed: [],
        careerInjuries: 0,
        gamesPlayedLastSeason: 12,
        seasonMinutesLeague: 840,
        seasonMinutesTotal: 840,
        isOnMarket: false,
        isRetired: false,
        camaraderieScore: 75,
        dailyItemsUsed: 0,
        careerInjuries: 0,
        gamesPlayedLastSeason: 0,
        seasonMinutesLeague: 0,
        seasonMinutesTournament: 0,
        seasonMinutesExhibition: 0,
      },
      {
        id: 6,
        firstName: 'Tom',
        lastName: 'Wing',
        race: 'HUMAN',
        role: 'BLOCKER',
        speed: 25,
        power: 35,
        throwing: 17,
        catching: 26,
        kicking: 19,
        staminaAttribute: 33,
        leadership: 30,
        agility: 26,
        potentialRating: 3.6,
        age: 27,
        teamId: 102,
        createdAt: new Date(),
        updatedAt: new Date(),
        dailyStaminaLevel: 100,
        injuryStatus: 'HEALTHY',
        injuryRecoveryPointsNeeded: 0,
        injuryRecoveryPointsCurrent: 0,
        dailyItemsUsed: [],
        careerInjuries: 0,
        gamesPlayedLastSeason: 12,
        seasonMinutesLeague: 840,
        seasonMinutesTotal: 840,
        isOnMarket: false,
        isRetired: false,
        camaraderieScore: 75,
        dailyItemsUsed: 0,
        careerInjuries: 0,
        gamesPlayedLastSeason: 0,
        seasonMinutesLeague: 0,
        seasonMinutesTournament: 0,
        seasonMinutesExhibition: 0,
      }
    ];

    // Use the real match simulation system
    const result = await simulateEnhancedMatch(
      homeTeamPlayers,
      awayTeamPlayers,
      '101',
      '102',
      undefined, // No stadium for demo
      'exhibition'
    );

    res.json({
      success: true,
      result: {
        homeScore: result.homeScore,
        awayScore: result.awayScore,
        events: result.gameData.events,
        playerStats: result.gameData.playerStats,
        finalStats: result.gameData.finalStats,
        matchSummary: result.matchSummary
      }
    });
  } catch (error) {
    console.error('Demo match simulation error:', error);
    res.status(500).json({ 
      success: false, 
      error: 'Failed to simulate demo match' 
    });
  }
});

export default router;