import { Router, type Request, type Response, type NextFunction } from "express";
import { requireAuth } from "../middleware/firebaseAuth.js";

const router = Router();

/**
 * Reset all team standings and generate league schedule for Days 5-14
 * Admin endpoint for development purposes
 */
router.post('/reset-and-schedule', requireAuth, async (req: Request, res: Response, next: NextFunction) => {
  try {
    const userId = (req as any).user.claims.sub;
    
    // Only allow specific admin user for development
    if (userId !== 'dev-user-123') {
      return res.status(403).json({ message: "Admin access required for this operation" });
    }

    console.log('🧹 === STEP 1: CLEARING ALL RESULTS AND STANDINGS ===');
    
    // Import database client (matching pattern from other routes)
    const { getPrismaClient } = await import('../database.js');
    const prisma = await getPrismaClient();
    
    // Reset all team records to 0
    const teamUpdate = await prisma.team.updateMany({
      data: {
        wins: 0,
        losses: 0,
        points: 0
      }
    });
    console.log(`✅ Reset ${teamUpdate.count} team standings to 0`);
    
    // Delete all existing LEAGUE games (keep EXHIBITION and TOURNAMENT)
    const deletedGames = await prisma.game.deleteMany({
      where: {
        matchType: 'LEAGUE'
      }
    });
    console.log(`✅ Deleted ${deletedGames.count} league games`);
    
    // Skip player stats clearing for now - continue with scheduling
    console.log(`✅ Skipped player stats clearing (no dedicated stats table found)`);
    
    console.log('\n📅 === STEP 2: GENERATING PROPER LEAGUE SCHEDULE ===');
    
    // Use the new working schedule generation service
    const { ScheduleGenerationService } = await import('../services/scheduleGenerationService.js');
    const scheduleResult = await ScheduleGenerationService.generateCompleteSchedule();
    
    if (scheduleResult.error) {
      throw new Error(`Schedule generation failed: ${scheduleResult.error}`);
    }
    
    console.log(`✅ Generated ${scheduleResult.totalMatches} matches across ${scheduleResult.leaguesScheduled} leagues`);
    
    // The schedule has been generated by the service above
    const totalGamesCreated = scheduleResult.totalMatches;
    
    console.log(`\n🎉 === COMPLETE: Generated ${totalGamesCreated} league games ===`);
    
    res.json({
      success: true,
      message: "Reset and schedule generation completed successfully",
      summary: {
        teamsReset: teamUpdate.count,
        gamesDeleted: deletedGames.count,
        statsCleared: 0,
        gamesCreated: totalGamesCreated
      },
      details: {
        eachTeamPlays: 10,
        daysScheduled: "5-14",
        gameTime: "3PM EDT daily with 15-minute intervals"
      }
    });
    
  } catch (error) {
    console.error('❌ Error in reset and schedule:', error);
    next(error);
  }
});

/**
 * Generate matches for a single day ensuring each team plays exactly once
 * Uses round-robin rotation for fair scheduling
 */
function generateDayMatches(teams: any[], day: number): { homeTeam: any, awayTeam: any }[] {
  const matches: { homeTeam: any, awayTeam: any }[] = [];
  const numTeams = teams.length;
  
  if (numTeams < 8) return matches;
  
  // Round-robin algorithm: rotate teams to create balanced schedule
  const teamList = [...teams];
  const rotationOffset = (day - 5) % (numTeams - 1); // Days 5-14 mapped to 0-9
  
  // Apply rotation
  for (let i = 0; i < rotationOffset; i++) {
    teamList.push(teamList.shift());
  }
  
  // Create 4 matches from 8 teams
  for (let i = 0; i < 4; i++) {
    const homeTeam = teamList[i];
    const awayTeam = teamList[i + 4];
    
    matches.push({
      homeTeam: homeTeam,
      awayTeam: awayTeam
    });
  }
  
  return matches;
}

export default router;