name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}

    - name: Configure Docker for Google Cloud
      run: gcloud auth configure-docker us-east5-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -f Dockerfile.production -t us-east5-docker.pkg.dev/direct-glider-465821-p7/realm-rivalry/production:${{ github.sha }} .
        docker tag us-east5-docker.pkg.dev/direct-glider-465821-p7/realm-rivalry/production:${{ github.sha }} us-east5-docker.pkg.dev/direct-glider-465821-p7/realm-rivalry/production:latest

    - name: Push Docker image
      run: |
        docker push us-east5-docker.pkg.dev/direct-glider-465821-p7/realm-rivalry/production:${{ github.sha }}
        docker push us-east5-docker.pkg.dev/direct-glider-465821-p7/realm-rivalry/production:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy realm-rivalry \
          --image us-east5-docker.pkg.dev/direct-glider-465821-p7/realm-rivalry/production:${{ github.sha }} \
          --platform managed \
          --region us-east5 \
          --allow-unauthenticated \
          --service-account realm-rivalry-runner@direct-glider-465821-p7.iam.gserviceaccount.com \
          --set-env-vars NODE_ENV=production,GOOGLE_CLIENT_ID=108005641993-e642ered12jj7ka6unpqhgjdls92c0u8.apps.googleusercontent.com \
          --set-secrets DATABASE_URL=database-url:latest,SESSION_SECRET=session-secret:latest,GOOGLE_CLIENT_SECRET=google-client-secret:latest \
          --memory 2Gi \
          --cpu 1 \
          --concurrency 80 \
          --max-instances 10 \
          --port 8080 \
          --timeout 300s