name: Frontend Only - Firebase Deploy

on:
  workflow_dispatch:
    inputs:
      backend_url:
        description: 'Backend URL to connect to'
        required: true
        default: 'https://realm-rivalry-backend-108005641993.us-east5.run.app'

env:
  PROJECT_ID: direct-glider-465821-p7

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Test backend connectivity
      run: |
        echo "🧪 Testing backend connectivity..."
        curl -f "${{ github.event.inputs.backend_url }}/health" || {
          echo "❌ Backend not responding at ${{ github.event.inputs.backend_url }}"
          exit 1
        }
        echo "✅ Backend is responding"

    - name: Build frontend
      run: |
        echo "🔨 Building frontend with backend: ${{ github.event.inputs.backend_url }}"
        npm run build
        echo "✅ Frontend build completed"
      env:
        VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
        VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
        VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
        VITE_API_BASE_URL: ${{ github.event.inputs.backend_url }}

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy to Firebase
      run: |
        echo "🚀 Deploying to Firebase..."
        firebase deploy --project ${{ env.PROJECT_ID }}
        echo "✅ Frontend deployed to https://realmrivalry.com"

    - name: Test deployment
      run: |
        echo "🧪 Testing frontend deployment..."
        STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://realmrivalry.com)
        if [ "$STATUS" = "200" ]; then
          echo "✅ Frontend is live at https://realmrivalry.com"
        else
          echo "❌ Frontend deployment failed (HTTP $STATUS)"
          exit 1
        fi