name: Create Neon Branch on Git Branch Creation

on:
  create:

jobs:
  create_neon_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Create Neon Branch
        uses: neondatabase/create-branch-action@v5
        with:
          project_id: bitter-night-05796896
          branch_name: ${{ github.ref_name }}
          api_key: ${{ secrets.NEON_API_KEY }}

      - name: Output Neon Branch ID
        run: echo "Successfully created Neon branch with name ${{ steps.create_neon_branch.outputs.branch_id }}"
